trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy
    jobs:
      - job: DeployToAnsibleServer
        displayName: Trigger Ansible on Remote Server
        steps:
          - script: |
              ssh -i  C:\Users\HP\Downloads '.\Ansible_key (1).pem' azureuser@20.40.52.190 \
              "ansible-playbook -i https://github.com/harshraj7040/React-DevOps-Project/blob/main/personal-finance-tracker-main/deploy-react.yaml"
            displayName: Trigger Ansible Playbook on Remote Server
